import 'package:jozapp_flutter/models/types.dart';

const Json en = {
  "main.profile": "My Profile",
  "main.wallet": "My Wallet",
  "main.services": "My Services",
  "main.trans": "Transactions",
  "cur.iqd.s": "IQD",
  "cur.iqd.l": "Iraqi Dinar",
  "cur.iqd.sym": "IQD",
  "cur.irr.s": "ITC",
  "cur.irr.l": "ITC",
  "cur.irr.sym": "ITC",
  "cur.aud.s": "AUD",
  "cur.aud.l": "Australian Dollar",
  "cur.aud.sym": "\$",
  "cur.usd.s": "USD",
  "cur.usd.l": "US Dollar",
  "cur.usd.sym": "\$",
  "cur.eur.s": "EUR",
  "cur.eur.l": "Euro",
  "cur.eur.sym": "€",
  "cur.gbp.s": "GBP",
  "cur.gbp.l": "British Pond",
  "cur.gbp.sym": "£",
  "cur.aed.s": "AED",
  "cur.aed.l": "UAE Dirham",
  "cur.aed.sym": "AED",
  "cur.cad.s": "CAD",
  "cur.cad.l": "Canadian Dollar",
  "cur.cad.sym": "\$",
  "cur.try.s": "TRY",
  "cur.try.l": "Turkish Lira",
  "cur.try.sym": "₺",
  "cur.cny.s": "Yuan",
  "cur.cny.l": "China Yuan",
  "cur.cny.sym": "CNY",
  "OrderStatus.issued": "Open",
  "OrderStatus.accepted": "Accepted",
  "OrderStatus.rejected": "Rejected",
  "OrderStatus.canceled": "Canceled",
  "OrderStatus.suspended": "Suspended",
  "OrderStatus.issued.s": "O",
  "OrderStatus.accepted.s": "A",
  "OrderStatus.rejected.s": "R",
  "OrderStatus.canceled.s": "C",
  "OrderStatus.suspended.s": "S",
  "OrderTypes.all2.s": "All",
  "OrderTypes.topUp.s": "TU",
  "OrderTypes.withdraw.s": "W",
  "OrderTypes.exchange.s": "E",
  "OrderTypes.transfer.s": "T",
  "OrderTypes.fee.s": "F",
  "OrderTypes.All.l": "(All Order types)",
  "OrderTypes.airplaneTicket.s": "Airplane Ticket",
  "OrderTypes.otp.s": "OTP",
  "OrderTypes.all2.l": "All",
  "OrderTypes.topUp.l": "Top-up",
  "OrderTypes.withdraw.l": "Withdraw",
  "OrderTypes.exchange.l": "Exchange",
  "OrderTypes.transfer.l": "Transfer",
  "OrderTypes.fee.l": "Fee",
  "OrderTypes.airplaneTicket.l": "Airplane Ticket",
  "OrderTypes.otp.l": "OTP",
  "auth.forget_pass": "Forgot Password",
  "auth.contact_us": "Contact us",
  "profile.your_wallet": "Your Wallet Number",
  "profile.about_us": "About Us",
  "profile.change_password": "Change Password",
  "profile.user_settings": "User Settings",
  "profile.change_lang": "Language",
  "profile.branch_info": "Branch Info",
  "profile.logout": "Sign Out",
  "login": "Sign In",
  "register": "Registration",
  "auth.phone_number": "Phone Number",
  "auth.password": "Password",
  "auth.confirm": "Confirm Password",
  "auth.curPassword": "Current Password",
  "auth.newPassword": "New Password",
  "auth.displayName": "Display Name",
  "auth.logout": "Sign Out",
  "auth.code": "Verification Code",
  "auth.verify_code": "Verify Code",
  "auth.register_user": "Register User",
  "auth.user_information": "User Information",
  "auth.set_new_password": "Set New Password",
  "auth.set_password": "Set Password",
  "auth.enter_ver_code": "Enter verification code you have received",
  "auth.send_sms": "Send SMS",
  "auth.select_branch": "Select Branch",
  "auth.no_branch": "No Branch",
  "err.userAlreadyExist": "A User with this phone number already registered",
  "err.userNotExist": "No User with this phone number found",
  "err.sendingVerificationCode": "Error sending Verification code",
  "err.verifyVerificationCode": "Verification code is not valid.",
  "err.invalid_phone": "Invalid Phone Number",
  "err.invalid_password": "Invalid Password",
  "err.tooShortVerifyCode": "Verification code entered is too short",
  "err.displayName": "Display Name is too short",
  "err.passwords_match": "Entered Passwords do not match",
  "err.set_password": "Error occurred in setting new password",
  "main.services.choice.service": "Available Services",
  "OrderTypes.topUp.t": "Top Up",
  "OrderTypes.topUp.ts": "Select one for Top up",
  "OrderTypes.withdraw.t": "Withdraw",
  "OrderTypes.withdraw.ts": "Select one for Withdraw",
  "OrderTypes.transfer.t": "Transfer",
  "OrderTypes.transfer.ts": "Select one for Transfer",
  "Back": "Back",
  "Next": "Next",
  "Cancel": "Cancel",
  "Confirm": "Confirm",
  "err.invalid_amount": "Invalid Amount",
  "err.invalid_wallet_number": "Invalid Wallet Number",
  "err.insufficient_liquidity": "Insufficient liquidity",
  "amount": "Amount {0}",
  "available": "Available {0}",
  "profile.wallet_number": "Wallet Number",
  "q.do_that": "Are You Sure For Doing That?",
  "q.cancel": "Are you sure to cancel this action?",
  "q.cancel_order": "Are you sure to cancel this order?",
  "msg.order_canceled": "Order has been canceled successfully",
  "orders.open": "Open Orders",
  "successfully": "Successful !",
  "msg.set_password_was": "Set Password was",
  "msg.ticket_issue": "Ticket Issue",
  "msg.user_creation": "Your User creation was",
  "msg.change_password": "Change Password was",
  "msg.your_operation": "Your {0} was",
  "txt.dest_cur": "Destination Currency {0}",
  "Yes": "Yes",
  "No": "No",
  "Question": "Question",
  "txt.load_more": "Load More",
  "order.type": "Order Type",
  "order.amount": "Order Amount",
  "order.issue_date": "Issue Date",
  "order.view": "Order View",
  "profile.welcome": "Welcome {0}",
  "profile.current_balance": "Current Balance",
  "profile_def_currency": "Default Currency",
  "profile.address": "Address",
  "profile.phone": "Phone",
};